const LOAD_START = "LOAD_START"
const LOAD_SUCCESS = "LOAD_SUCCESS" 
const LOAD_FAILURE = "LOAD_FAILURE"
const SUBMIT_TODO = "SUBMIT_TODO"
const EDIT_TODO = "EDIT_TODO"
const DEL_TODO = "DEL_TODO"
const SELECT_TODO = "SELECT_TODO"

export {LOAD_START, LOAD_SUCCESS, LOAD_FAILURE, SUBMIT_TODO, EDIT_TODO, DEL_TODO, SELECT_TODO}