const LOAD_START = "LOAD_START"
const LOAD_SUCCESS = "LOAD_SUCCESS" 
const LOAD_FAILURE = "LOAD_FAILURE"
const SUBMIT_TODO_LIST = "SUBMIT_TODO_LIST"
const EDIT_TODO = "EDIT_TODO"
const DEL_TODO = "DEL_TODO"
const SELECT_TODO = "SELECT_TODO"
const CREATE_LIST_START = "CREATE_LIST_START"
const CREATE_LIST_SUCCESS = "CREATE_LIST_SUCCESS"
const CREATE_LIST_FAIL = "CREATE_LIST_FAIL"
const ADD_TODO_START = "ADD_TODO_START"
const ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS"
const ADD_TODO_FAIL = "ADD_TODO_FAIL"

export {LOAD_START, CREATE_LIST_START, CREATE_LIST_SUCCESS, CREATE_LIST_FAIL, LOAD_SUCCESS, LOAD_FAILURE, SUBMIT_TODO_LIST, EDIT_TODO, DEL_TODO, SELECT_TODO,
    ADD_TODO_FAIL, ADD_TODO_START, ADD_TODO_SUCCESS}
